name: mhkit-dolfyn-gui
channels:
  - conda-forge
dependencies:
  - python=3.11
  - mhkit>=1.0.1
  - numpy>=2.0
  - libnetcdf
  - netcdf4
  - hdf5
  - pyyaml
  - psutil
  - pip
  - pip:
    - PySide6>=6.6.0,<6.11
